image:
  file: .gitpod.Dockerfile

tasks:
  - init: sdk use java 16.0.1.hs-adpt
    command: cd casino; mvn install “-DskipUiTests=true"

ports:
  # used by virtual desktop and vnc, supports JavaFX
  - port: 6080

vscode:
  extensions:
    - ritwickdey.liveserver
